application:
  port: 13000
  hmac_secret: "faa52941-aa95-42db-ad5f-c5598b3d4165"
  redis_uri: "redis://127.0.0.1:6379"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "it-09@ace-tec.com"
  authorization_token: "7b4ff3b1-9919-41e5-9eb6-a087f52c4a3c"
  timeout_milliseconds: 10000
