application:
  port: 13000
  hmac_secret: "faa52941-aa95-42db-ad5f-c5598b3d4165"
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "input-valid-secret-token"
  timeout_milliseconds: 10000
